# Generated by Django 4.1 on 2022-08-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Marca', models.CharField(max_length=50)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Disponibles', models.IntegerField(blank=True, null=True)),
                ('Sku', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
