# Generated by Django 4.1 on 2022-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
